stages:
  - build
  - build-chromium
  - publish
  - test

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  NAMESPACE: mrofi/gitlab-ci-pipeline-php
  NAMESPACE_COMPOSER_1: mrofi/gitlab-ci-pipeline-php-composer-1

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

Alpine 7.2:
  stage: build
  variables:
    IMAGE_VERSION: "7.2-alpine"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.2/alpine/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g tests/goss-7.2.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION

    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE_COMPOSER_1:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE_COMPOSER_1:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg COMPOSER_VERSION=1 -t $NAMESPACE_COMPOSER_1:$IMAGE_VERSION -f php/7.2/alpine/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE_COMPOSER_1:$IMAGE_VERSION goss -g tests/goss-7.2.yaml v
    - docker push $NAMESPACE_COMPOSER_1:$IMAGE_VERSION
  when: always
